Provide LitVirtualizer.js for side-effect-free imports
PolymerLabs/uni-virtualizer pull request #119
Opened 2022-03-15 19:20 UTC by hunterloftis

Currently, any component using `LitVirtualizer` must also implicitly define `<lit-virtualizer>` in the global `customElements` registry.

This attempts to maintain backwards-compatibility with current behaviors, where `import { LitVirtualizer} from  '@lit-labs/virtualizer'` auto-registers the element, while adding a side-effect-free `import { LitVirtualizer } from '@lit-labs/virtualizer/LitVirtualizer.js'`.

I'm not sure if this really accomplishes that, though, because:

- The tests don't seem to be runnable.
- The build step creates the files I would expect (including `LitVirtualizer.js`) but I don't see any information on how this package is published.

Changes & feedback welcome. My goal is to make it possible to extend `LitVirtualizer` without modifying the global `customElements` registry.

2022-03-16 10:31 UTC, joekukish commented
@hunterloftis Might be a good time to follow this: https://open-wc.org/guides/developing-components/publishing/#do-export-side-effects-separately and declare it as "sideEffects" in the package.json

2022-03-16 10:35 UTC, joekukish commented
@graynorton Could be a good time to make a breaking change and move lit-virtualizer to the root (`packages/lit-virtualizer/lit-virtualizer.ts`) and follow the best practices to publish web components.

2022-03-16 17:17 UTC, joekukish commented
@hunterloftis normally you would define the file at package root (`packages/lit-virtualizer/lit-virtualizer.ts` instead of `packages/lit-virtualizer/src/lit-virtualizer.ts`, then add the indication in the package.json.

2022-03-16 22:08 UTC, justinfagnani commented
@hunterloftis I made https://github.com/PolymerLabs/uni-virtualizer/pull/121 to get tests running. The tests need to be built out, so it's not that blocking here, but FYI.

This PR looks good to me so far, but we'll need an entry in packages/lit-virtualizer/package.json#files for the new file.

2022-03-16 22:09 UTC, justinfagnani requested changes
Thanks! Please add a changelog entry too.

2022-03-16 22:09 UTC, justinfagnani commented on packages/lit-virtualizer/src/LitVirtualizer.ts
> +/**
We need this file in package.json#files so it'l get to npm

2022-03-17 00:25 UTC, justinfagnani approved these changes
LGTM! Checking with @graynorton offline to see if he has any comments.

2022-03-17 00:25 UTC, justinfagnani commented on packages/lit-virtualizer/package.json
> +    "version": "0.8.0",
This isn't a breaking change, so I think we can stick with 0.7. Let's do 0.7-pre.3

2022-03-17 16:26 UTC, justinfagnani commented on packages/lit-virtualizer/package.json
> +    "version": "0.8.0",
@hunterloftis could we get this changed?

2022-03-17 17:32 UTC, justinfagnani requested changes

2022-03-17 17:32 UTC, justinfagnani commented on packages/lit-virtualizer/CHANGELOG.md
> +## [0.8.0] - 2022-03-16
This needs to change to 0.7.0-pre.3 too

2022-03-17 18:49 UTC, hunterloftis commented on packages/lit-virtualizer/CHANGELOG.md
> +## [0.8.0] - 2022-03-16
🤦  updated!

2022-03-17 20:34 UTC, justinfagnani approved these changes

2022-03-17 21:45 UTC, merged

2022-03-21 16:34 UTC, hunterloftis commented
@justinfagnani could you or @graynorton publish the latest version on npm?

2022-03-21 18:15 UTC, hunterloftis commented
That sounds great, thank you @graynorton!